### ISSUE TITLE
Where can I find the latest sources (version 2.2.1.0902) ?

### ISSUE THREAD

**Issue by theCassiopeia** [Makeblock-official/mBlock#14]
I downloaded a couple of days ago the latest version of mblock from http://www.mblock.cc/.
Its 'behavior' does not match the latest source code versions here on github, so I wondered where I could find the latest updates on GITHUB?
I noted it since the menu item "check SW update" is not available here in github in the mblock.as module. 
The modules are available in the downloaded package, that's clear.

**Comment by kurtdevocht** [comment]
+1
The source code here should match the latest version available for download

**Comment by zhanglimin** [comment]
+1

**Comment by cmcknight** [comment]
I would suggest dropping a note to support@makeblock.cc. Pioneer Chen is very good about chasing these details down and getting them corrected.  :-)

**Comment by bigeyex** [comment]
resolved
