### ISSUE TITLE
How do you make extensions?

### ISSUE THREAD

**Issue by GlennGeenen** [Makeblock-official/mBlock#15]
Is there any documentation how to create extensions for mBlock? I couldn't find information on it. The extension manager expects a zip file, what should be in this zip file? 

I have scratch extensions I want to add to mBlock so that you can control the mBot with a leap motion or kinect controller. I see in the source files that the mBlock extensions are based on the json syntax used in scratch extensions. What are the required fields, required files?

**Comment by piif** [comment]
I've got the same question : I tried to adapt a simple scratch extension i wrote, but it doesn't work.
The only result i can get is reporter blocks which return empty values.
It seems also that mBlock wants something connected even if my extension don't need to communicate with external devices.

Some basic examples should help greatly

**Comment by jm4r7in** [comment]
+1

**Comment by ignacioandcorral** [comment]
yes the same here

**Comment by libertytrooper** [comment]
+1

**Comment by The-Best-Codes** [comment]
To make an mBlock extension, use:
https://ext.mblock.cc/
