### ISSUE TITLE
mBot "play tone on note" block makes mbot crash

### ISSUE THREAD

**Issue by kurtdevocht** [Makeblock-official/mBlock#17]
In Scratch mode (not Arduino mode): When the block "play tone on note" is executed with tones "D3", "E5" or "A7" the mBot stops responding.

Only after the serial port is disconnected and reconnected (by clicking "Connection" > "Serial Port" > "COMx") the mBot will be responsive again.

**Comment by cmcknight** [comment]
I'm using Scratch mode, but due to USB issues with El Capitan, I'm connected via the 2.4GHz wireless and I am not seeing this issue. I do have to occasionally disconnect the dongle and reconnect it though.
