### ISSUE TITLE
After updating firmware for new mbot via COM3, remote control is not working anymore

### ISSUE THREAD

**Issue by joanmarcmas** [Makeblock-official/mBlock#25]
Dear all,

After updating the firmware, the mbot no longer boots with three beeps and flashing lights and no longer respond to the IR remote control.

Is there a way, to go back to the factory firmware before the update ?

I cann't no longer control it via IR or play with it without programming.

Thanks in advace

**Comment by AngelAlvarado** [comment]
Same here.
Windows 10. 
mBlock_win_V3.4.2

I already tried reseting to factory settings but mBlock does not longer respond.

 https://makeblockshop.eu/blogs/known-issues/112896196-restore-mbot-out-of-the-box-functions
