### ISSUE TITLE
[Security issue] Installer is only provided via http (not https)

### ISSUE THREAD

**Issue by green-coder** [Makeblock-official/mBlock#35]
Some users might feel not safe installing software distributed via http without any mean to know if it was altered between the website and the browser.

**Comment by green-coder** [comment]
A quick way to fix it could be to publish the SHA checkum of the installer on Github (which is using https) **OR** to use Github to serve the zip file (there is a release feature for that) as it is using https.

**Comment by bigeyex** [comment]
[Github release](https://github.com/Makeblock-official/mBlock/releases) added, solving this issue.
