### ISSUE TITLE
mbot specific block cause compilation failures

### ISSUE THREAD

**Issue by Achifaifa** [Makeblock-official/mBlock#38]
We've been using mbots to show basic robotics to kids. Today, for no apparent reason, all programs failed to compile and upload when blocks like <if remote [button] pressed> or [set led] were used anywhere in the program. I've been looking into it for quite some time now, and I just can't find any explanation. 

Compilation fails in 4 different computers (Win XP, win 7, win 8, win 10) and in >8 different mbot boards, with the proper firmware previously loaded. 

Any clues about what's happening?

**Comment by bigeyex** [comment]
This issue has been passed for a long time and numerous new versions are released. Please re-open if the issue is still there.
