### ISSUE TITLE
mBlock 3.3.2 Mac download is actually 3.3.1

### ISSUE THREAD

**Issue by aysiu** [Makeblock-official/mBlock#39]
On the mBlock website, there's a download labeled mBlock_mac_v3.3.2.zip. When you unzip it, there's an app labeled mBlock_v3.3.2, but when you look at the info on it, it says 3.3.1, and when you launch it up, mBlock complains there's an updated version to download... there isn't—that is the updated version.

So either you need to change the info to be 3.3.2 or put the actual 3.3.2 app inside the 3.3.2 .zip file.

Thanks!

**Comment by bigeyex** [comment]
New versions released, closing the issue.
