### ISSUE TITLE
How to help translating ?

### ISSUE THREAD

**Issue by SebCanet** [Makeblock-official/mBlock#41]
HI,
I made French translation, but I would to correct some sentences and add new ones, how can I do ?

Thanks.

**Comment by intoeetive** [comment]
@SebCanet you need to fork this repo, make changes and then make pull request

**Comment by SebCanet** [comment]
ok, thank you, Ill do it.

**Comment by SebCanet** [comment]
I don't think...it seems there's no more activity on this depot.
The translation way has changed and I see nowhere the file 'locale.xlsx' needed....

**Comment by intoeetive** [comment]
It's here: https://github.com/Makeblock-official/mBlock/blob/master/source/src/locale/locale.xlsx

**Comment by SebCanet** [comment]
But it's 10 months old...for version 3.2.1. Do they still use it ?

**Comment by intoeetive** [comment]
No idea, sir =)

They claim it to be open source, but looking at messages on forums, I can say it's probably not.

**Comment by SebCanet** [comment]
And I have no more mail answer ! Dammit...

**Comment by cmcknight** [comment]
You might try going on the forums and posting the question to @tec_support.

**Comment by bigeyex** [comment]
This is the way: http://www.mblock.cc/posts/note-for-translators
