### ISSUE TITLE
How to install to Linux Debian?

### ISSUE THREAD

**Issue by rusyabob** [Makeblock-official/mBlock#42]
How to install to Linux Debian?

**Comment by cmcknight** [comment]
To install Makeblock on Debian, you will need to set it up in a virtual machine that supports Windows. Not sure if Wine will work properly. Adobe chose to drop support for Adobe Air for Linux, and unfortunately the Scratch team wrote their offline editor (the basis of mBlock) using Adobe Air.  :-(

**Comment by bigeyex** [comment]
We are working on a Linux version. Now it is on the early preview stage. [Try it](https://github.com/Makeblock-official/mBlock/releases/tag/V4.0.0-linux-ep1) if you are interested.
