### ISSUE TITLE
mBlock Arduino code generation for reset time and timer incorrect in wait until

### ISSUE THREAD

**Issue by simmunity** [Makeblock-official/mBlock#44]
code uses uninitialized "currentTime" variable and never references "lastTime" variable in while statement:  This is with release version mBlock downloaded 10/5/16

    double dotRate;
    dotRate = (200) / (60);
. . .
// is currently:
            lastTime = millis()/1000.0;
            while(!((currentTime) > ((7) / (dotRate))));

// should be:
            lastTime = millis()/1000.0;
            while(!((millis()/1000.0) > (lastTime + (7) / (dotRate))));

**Comment by bigeyex** [comment]
close that for now since there's an update. Please reopen if the problem is still there.
