### ISSUE TITLE
GPL violation, mBlock v3.4.5

### ISSUE THREAD

**Issue by green-coder** [Makeblock-official/mBlock#45]
Makeblock is currently violating the terms of the GPL v2 as it published a compiled version of the GPL-based software without providing its source code.

Please update the git repository to contains the source code used to build the released software. Thank you.

**Comment by bigeyex** [comment]
Resolved. Looking forward to your PR. (note that the active version is not on the master branch now - the codebase is going under a structural change).

**Comment by green-coder** [comment]
I do not plan to do a PR in the short term, I just wanted to have a read access to the source code for my own education.
