### ISSUE TITLE
mBlock 4.0 linux: cannot connect to the 2.4G device as a user

### ISSUE THREAD

**Issue by on4tux** [Makeblock-official/mBlock#51]
I tried the alpha native release of mBlock on linux but cannot connect to the 2.4G device as a normal user. It does work running as root. Can you add a procedure to change permissions?

The workaround on http://forum.makeblock.com/t/mblock-working-with-mbot-on-linux-but-not-wireless/3198/15 does not work, I don't see the /dev/hidraw* files

**Comment by bigeyex** [comment]
A new linux version is released. It should add proper permissions in the first run.
