### ISSUE TITLE
Functions are deactivated in mBlock 3.4.6

### ISSUE THREAD

**Issue by otmezger** [Makeblock-official/mBlock#63]
Hi, 
I was wondering why some functions are not active, like for example the events (Q2) or the "When on board pressed" (Q1). See screenshot. What config am I missing? 

Thanks
![bildschirmfoto_2017-04-14_um_10_37_57_am](https://cloud.githubusercontent.com/assets/2758346/25038387/e68c22ee-20fe-11e7-98c6-2d874ad37026.png)

**Comment by bigeyex** [comment]
Hi, 
When you quit Arduino mode, this block will become available.
This is because the Arduino compiling method mBlock use does not support multi threading, 
so header blocks can be only used in Scratch mode.

**Comment by otmezger** [comment]
ok, thanks. not even the "When on board button pressed"? 

It seems that it's not compatible as well, even if it's in the Robots section
![bildschirmfoto 2017-04-14 um 11 04 45 am](https://cloud.githubusercontent.com/assets/2758346/25039151/8b3e9760-2102-11e7-8fef-a24f40564777.png)

**Comment by bigeyex** [comment]
The way mBlock works is converting blocks into Arduino code. The PC is a powerful device, with a large screen and great computing power; the Arduino chip in the robot is not. 

Thus those blocks that make the panda rotate, or run events in parallel, can be only run on PC, not the Arduino-based robot. Even "when button pressed" is a kind of event blocks. Please use repeat and "button ... pressed" instead.

Makeblock is working on a more powerful robot that may support event system - but it is not the entry-level mBot.
