### ISSUE TITLE
I can't seem to install npm

### ISSUE THREAD

**Issue by dnzayan** [Makeblock-official/mBlock#89]
I cannot install.

npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

> bluetooth-serial-port@2.2.7 install C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port
> node-gyp configure build

C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port>if not defined npm_config_node_gyp (node "C:\Users\Deniz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "C:\Users\Deniz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  BluetoothSerialPort.cc
  DeviceINQ.cc
  BTSerialPortBinding.cc
  BluetoothHelpers.cc   
  win_delay_load_hook.cc
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(44): warning C4996: '_WSAQuerySetA::dwSize': Use WSAQUERY
SETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-ser
ial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1320): note: see declaration of '_WSAQuerySetA::dwSize'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(45): warning C4996: '_WSAQuerySetA::dwNameSpace': Use WSA 
QUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoot 
h-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1325): note: see declaration of '_WSAQuerySetA::dwNameSpace'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(46): warning C4996: '_WSAQuerySetA::lpServiceClassId': Us 
e WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\blu 
etooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1322): note: see declaration of '_WSAQuerySetA::lpServiceClassId'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(47): warning C4996: '_WSAQuerySetA::dwNumberOfCsAddrs': U 
se WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bl 
uetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1331): note: see declaration of '_WSAQuerySetA::dwNumberOfCsAddrs'c:\users\den
  iz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(40): warning C4996: 'WSAStringToAddressA': Use WSAStringT 
  oAddressW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3566): note: see declaration of 'WSAStringToAddressA'c:\users\deniz\desktop\mb 
  lock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(48): warning C4996: '_WSAQuerySetA::lpszContext': Use WSAQUERYSETW instead or de 
  fine _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1327): note: see declaration of '_WSAQuerySetA::lpszContext'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(66): warning C4996: 'Nan::Callback::Call': was  
declared deprecatedc:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(61): warning C4996: '_WSAQuerySetA::lp 
csaBuffer': Use WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\no 
de_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\program files (x86)\windows kits\10\ 
  include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'

c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(77): warning C4996: 'Nan::Callback::Call': was  
declared deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\users\deniz\desktop\mblock-master\no
  de_modules\bluetooth-serial-port\src\windows\deviceinq.cc(52): warning C4996: 'WSALookupServiceBeginA': Use WSALookupServiceBeginW() instead or define _ 
  WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3628): note: see declaration of 'WSALookupServiceBeginA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(58): warning C4996: 'WSALookupServiceNextA': Use WSALooku
pServiceNextW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bl 
uetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3679): note: see declaration of 'WSALookupServiceNextA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(104): warning C4996: 'Nan::Callback::Call': was declared  
deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(130): warning C4996: 'Nan::Callback::Call': was 
 declared deprecatedc:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(146): warning C4996: '_WSAQuerySetA:: 
dwSize': Use WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_ 
modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'c:\program files (x86)\windows kits\10\ 
  include\10.0.17763.0\um\winsock2.h(1320): note: see declaration of '_WSAQuerySetA::dwSize'

c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(147): warning C4996: '_WSAQuerySetA::dwNameSpace': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo
th-serial-port\build\BluetoothSerialPort.vcxproj]
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(201): warning C4996: 'Nan::Callback::Call': was 
 declared deprecatedc:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1325): note: see declaration of '_WSAQuerySetA::dwNameSpace'
 [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(168): warning C4996: '_WSAQuerySetA::lpcsaBuffer': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(172): warning C4996: '_WSAQuerySetA::lpcsaBuffer': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(248): error C2661: 'v8::String::Utf8Value::Utf8
Value': no overloaded function takes 2 arguments [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxpro 
j]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(249): error C2039: 'ToChecked': is not a member 
 of 'v8::Maybe<int>' [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(180): warning C4473: 'sscanf_s' : not enough arguments pa 
ssed for format string [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\appdata\local\node-gyp\cache\6.9.0\include\node\v8.h(1487): note: see declaration of 'v8::Maybe<int>'
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(180): note: placeholders and their parameters expect 2  
  variadic arguments, but 1 were provided
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(180): note: the missing variadic argument 2 is required 
   by format string '%18[^)]'
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(180): note: this argument is used as a buffer size      
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(185): warning C4996: '_WSAQuerySetA::lpszServiceInstanceN 
ame': Use WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_mod 
ules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\btserialportbinding.cc(358): warning C4996: 'Nan::Callback::Call': was 
 declared deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1321): note: see declaration of '_WSAQuerySetA::lpszServiceInstanceName'c:\use 
  rs\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'

c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(151): warning C4996: 'WSALookupServiceBeginA': Use WSALoo
kupServiceBeginW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules
\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3628): note: see declaration of 'WSALookupServiceBeginA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(164): warning C4996: 'WSALookupServiceNextA': Use WSALook 
upServiceNextW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\b 
luetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3679): note: see declaration of 'WSALookupServiceNextA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(172): warning C4996: 'WSAAddressToStringA': Use WSAAddres 
sToStringW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluet 
ooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3507): note: see declaration of 'WSAAddressToStringA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(267): warning C4996: 'Nan::Callback::Call': was declared  
deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(270): warning C4996: 'Nan::Callback::Call': was declared  
deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(299): warning C4996: 'Nan::Callback::Call': was declared  
deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(302): warning C4996: 'Nan::Callback::Call': was declared  
deprecated [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(338): error C2661: 'v8::String::Utf8Value::Utf8Value': no 
 overloaded function takes 2 arguments [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(380): warning C4996: '_WSAQuerySetA::dwSize': Use WSAQUER
YSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-se 
rial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1320): note: see declaration of '_WSAQuerySetA::dwSize'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(381): warning C4996: '_WSAQuerySetA::dwNameSpace': Use WS
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1325): note: see declaration of '_WSAQuerySetA::dwNameSpace'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(396): warning C4996: '_WSAQuerySetA::dwOutputFlags': Use  
WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluet 
ooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1333): note: see declaration of '_WSAQuerySetA::dwOutputFlags'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(399): warning C4996: '_WSAQuerySetA::lpcsaBuffer': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(403): warning C4996: '_WSAQuerySetA::lpcsaBuffer': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(412): warning C4473: 'sscanf_s' : not enough arguments pa 
ssed for format string [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(412): note: placeholders and their parameters expect 2  
  variadic arguments, but 1 were provided
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(412): note: the missing variadic argument 2 is required 
   by format string '%18[^)]'
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(412): note: this argument is used as a buffer size      
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(413): warning C4473: 'sscanf_s' : not enough arguments pa 
ssed for format string [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(413): note: placeholders and their parameters expect 2  
  variadic arguments, but 1 were provided
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(413): note: the missing variadic argument 2 is required 
   by format string '%18[^)]'
  c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(413): note: this argument is used as a buffer size      
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(418): warning C4996: '_WSAQuerySetA::lpszServiceInstanceN 
ame': Use WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_mod 
ules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1321): note: see declaration of '_WSAQuerySetA::lpszServiceInstanceName'       
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(430): warning C4996: '_WSAQuerySetA::dwSize': Use WSAQUER 
YSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-se 
rial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1320): note: see declaration of '_WSAQuerySetA::dwSize'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(431): warning C4996: '_WSAQuerySetA::lpszContext': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1327): note: see declaration of '_WSAQuerySetA::lpszContext'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(433): warning C4996: '_WSAQuerySetA::lpServiceClassId': U
se WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bl 
uetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1322): note: see declaration of '_WSAQuerySetA::lpServiceClassId'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(434): warning C4996: '_WSAQuerySetA::dwNameSpace': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1325): note: see declaration of '_WSAQuerySetA::dwNameSpace'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(446): warning C4996: '_WSAQuerySetA::lpcsaBuffer': Use WS 
AQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetoo 
th-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1332): note: see declaration of '_WSAQuerySetA::lpcsaBuffer'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(449): warning C4996: '_WSAQuerySetA::lpszServiceInstanceN 
ame': Use WSAQUERYSETW instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_mod 
ules\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(1321): note: see declaration of '_WSAQuerySetA::lpszServiceInstanceName'       
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(387): warning C4996: 'WSALookupServiceBeginA': Use WSALoo 
kupServiceBeginW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules 
\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3628): note: see declaration of 'WSALookupServiceBeginA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(393): warning C4996: 'WSALookupServiceNextA': Use WSALook 
upServiceNextW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\b 
luetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3679): note: see declaration of 'WSALookupServiceNextA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(403): warning C4996: 'WSAAddressToStringA': Use WSAAddres 
sToStringW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluet 
ooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3507): note: see declaration of 'WSAAddressToStringA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(440): warning C4996: 'WSALookupServiceBeginA': Use WSALoo 
kupServiceBeginW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules 
\bluetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3628): note: see declaration of 'WSALookupServiceBeginA'
c:\users\deniz\desktop\mblock-master\node_modules\bluetooth-serial-port\src\windows\deviceinq.cc(444): warning C4996: 'WSALookupServiceNextA': Use WSALook 
upServiceNextW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings [C:\Users\Deniz\Desktop\mBlock-master\node_modules\b 
luetooth-serial-port\build\BluetoothSerialPort.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winsock2.h(3679): note: see declaration of 'WSALookupServiceNextA'
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  BluetoothSerialPortServer.vcxproj -> C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port\build\Release\\BluetoothSerialPortServer.no 
  de
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Deniz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Deniz\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\Deniz\Desktop\mBlock-master\node_modules\bluetooth-serial-port
gyp ERR! node -v v6.9.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bluetooth-serial-port@2.2.7 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bluetooth-serial-port@2.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Deniz\AppData\Roaming\npm-cache\_logs\2020-01-23T14_00_48_041Z-debug.log

**Comment by ghazalnzhr** [comment]
I'm having the same issue with `bluetooth-serial-port@2.2.7`, could someone please tell me how to fix it?
